name: protegelapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.6
  http: ^0.13.6
  chat_gpt_sdk: ^2.1.5
  otp_text_field: ^1.1.3
  firebase_core: ^2.14.0
  firebase_auth: ^4.6.3
  get: ^4.6.5
  cloud_firestore: ^4.8.2
  google_sign_in: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
