name: protegelapp
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_sound: ^8.4.2
  image_picker: ^0.8.4+4
  path_provider: ^2.0.5
  permission_handler: ^8.3.0
  file_picker: ^4.2.3
  datetime_picker_formfield: ^2.0.0
  intl: ^0.17.0

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.6
  http: ^0.13.6
  chat_gpt_sdk: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - images/

