// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYL82msZIDI-1DFyikljFoeDWpGvctro0',
    appId: '1:237344730188:web:0ade41236532e93d4098e9',
    messagingSenderId: '237344730188',
    projectId: 'protegelapp-a720c',
    authDomain: 'protegelapp-a720c.firebaseapp.com',
    storageBucket: 'protegelapp-a720c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9474Co3F9Y_XmDXsF9kxZhpcFx52UVEQ',
    appId: '1:237344730188:android:f37dac7cfbc138974098e9',
    messagingSenderId: '237344730188',
    projectId: 'protegelapp-a720c',
    storageBucket: 'protegelapp-a720c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBC7FX1p55EGQyoXKhnidzWfcrmbFncpo',
    appId: '1:237344730188:ios:65e1943c78f898724098e9',
    messagingSenderId: '237344730188',
    projectId: 'protegelapp-a720c',
    storageBucket: 'protegelapp-a720c.appspot.com',
    androidClientId: '237344730188-6tv4t3lovtht9e6v60f2s1vb0821d97k.apps.googleusercontent.com',
    iosClientId: '237344730188-54frkatlofd7dt2ral7902mulm0j93tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.protegelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBC7FX1p55EGQyoXKhnidzWfcrmbFncpo',
    appId: '1:237344730188:ios:65e1943c78f898724098e9',
    messagingSenderId: '237344730188',
    projectId: 'protegelapp-a720c',
    storageBucket: 'protegelapp-a720c.appspot.com',
    androidClientId: '237344730188-6tv4t3lovtht9e6v60f2s1vb0821d97k.apps.googleusercontent.com',
    iosClientId: '237344730188-54frkatlofd7dt2ral7902mulm0j93tl.apps.googleusercontent.com',
    iosBundleId: 'com.example.protegelapp',
  );
}
